select * from workshops;
select * from scheduler;
select * from clients;
select * from rooms;
select * from teachers;
select * from city;
select * from age_group;
select * from participate;
select * from groups_;
